# Taken from https://github.com/andyli/HaxeCI/blob/master/appveyor.yml
# Literally taken from kade engine github lol
version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko --version 2.3.0 -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 4.1.5 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  - haxelib install lime 7.9.0
  - RefreshEnv
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib install linc_luajit
  #why here's dublicate lmao
  - haxelib list

# No tests idk lol
build_script:
  - haxelib run lime build html5 -v -debug
  # haxelib run lime build linux

#absolute path cuz im dumb
after_build:
  - 7z a PsychEngine-HTML5.zip c:/projects/fnf-psychengine-0-3-2-hotfix/export/debug/html5/bin/
  
artifacts:
  - path: export/debug/html5/bin
    name: PsychEngine-HTML5
    type: zip
